export const SET_PROMOTED_LESSONS = 'SET_PROMOTED_LESSONS';
export const SET_ALL_LESSONS = 'SET_ALL_LESSONS';
export const SET_USER_LESSONS = 'SET_USER_LESSONS';
export const CLEAR_PROMOTED_LESSONS = 'CLEAR_PROMOTED_LESSONS';
