export const SET_PROMOTED_LESSONS = 'SET_PROMOTED_LESSONS';
export const CLEAR_PROMOTED_LESSONS = 'CLEAR_PROMOTED_LESSONS';
export const SET_PROMOTED_LESSONS_LOADING = 'SET_PROMOTED_LESSONS_LOADING';
